Projeto/Projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('produtos/', include('appProdutos.urls', namespace='produtos')),
    path('clientes/', include('appClientes.urls', namespace='clientes')),
    path('', include('plataforma.urls', namespace='plataforma'))
         
]

Projeto/plataforma/urls.py
from django.urls import path
from . import views

app_name = 'plataforma'

urlpatterns = [
    path('', views.home, name='home'),
    
    path('cadastro/', views.cadastro, name='cadastro'),

    path('alterar_senha/', views.alterar_senha, name='alterar_senha')
    
]

Projeto/plataforma/models.py
from django.db import models

# Create your models here.

Projeto/plataforma/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.messages import constants
from django.contrib import messages
from django.contrib.auth.models import User

from . models import models

# Create your views here.

HOME_PAGE = 'plataforma/base.html'
CADASTRO_PAGE = 'plataforma/cadastro.html'
TROCAR_SENHA_PAGE = 'plataforma/trocar_senha.html'


def home(request):
    return render(request, HOME_PAGE)

def login(request):
    try:
        if request.method == "POST":
            pass 
        
        
        # apenas parar de dar error, tira esse return depois
        return render(request, HOME_PAGE)
        
    except Exception as ex:
        msg = ex.args
        return render(request, HOME_PAGE, messages.add_message(request, constants.ERROR, f'{msg}'))
          

def cadastro(request):
    try:
         if request.method == "POST":
             return render(request, HOME_PAGE)
         
         
         
         else:
             username = request.POST.get('username')
             email = request.POST.get('email')
             senha = request.POST.get('senha')
             
             user = User.objects.get(username=username)
             
             if user:
                 return render(request, CADASTRO_PAGE, messages.add_message(request, constants.ERROR, 'usuario ja cadastrado'))
             
        
        
    except Exception as ex:
        msg = ex.args 
        return render(request, CADASTRO_PAGE)
    

def alterar_senha(request):
    return render(request,  TROCAR_SENHA_PAGE)

Projeto/plataforma/templates/plataforma/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title> Sistema Web </title>
    <link rel="stylesheet" href="{% static 'plataforma/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'plataforma/css/cadastro.css' %}">
    <link rel="stylesheet" href="{% static 'plataforma/css/reset.css' %}">
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <link rel="stylesheet" href="{% static 'appProdutos/css/bootstrap.min.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

</head>
<body>
<div class="logo" style="padding-top: 20px">
    <img src="{% static 'plataforma/img/3b874e1bacfab0d586c5534cc0c9b637-blue-star-square-logo.png' %}"  height="50px">
</div>

{% block main_content %}

 <main>
    <section class="formulario-login">

            <div class="container">
                    <form class="login-form" method="POST" action="{% url 'produtos:home' %}"> {% csrf_token %}
                        <div class="col-md-8">
                            <h2 style="color: #fff;">Login</h2>
                            <div class="form-group">
                                <label for="email" style="color: #fff;">E-mail:</label>
                                <input type="email" class="form-control" id="email" placeholder="Digite seu e-mail" required>
                            </div>
                            <div class="form-group">
                                <label for="senha" style="color: #fff;">Senha:</label>
                                <input type="password" class="form-control" id="senha" placeholder="Digite sua senha" required>
                            </div>
                            <div class="form-group">
                            <button id="confrim" type="submit" class="btn btn-primary">Entrar</button>
                            <a type="submit" class="btn btn-primary" href="{% url 'plataforma:cadastro' %}">cadastre-se</a>
                            </div>
                            <box-icon name='lock-open-alt'></box-icon>
                            <a href="{% url 'plataforma:alterar_senha' %}"  style="color: white; text-decoration: none;">Esqueceu a senha ?</a>
                        </div>
                    </form>

                </div>
        </section>
    </main>
{% endblock %}

{% include 'plataforma/footer.html' %}
</div>



</body>
</html>

Projeto/plataforma/templates/plataforma/cadastro.html
{% extends 'plataforma/base.html' %}

{% block main_content %}
<main>
    <section class="formulario-cadastro">
        <p align="center" style="color: white"> Cadastro de usuario </p>
            <div class="container-cadastro">
                <form class="cadastro-form" method="POST" action="{% url 'produtos:home' %}">
                    {% csrf_token %}
                    {{ form.codigo }}
                        <div class="form-group">
                          <label for="nome">Nome:</label>
                          <input type="text" class="form-control" id="nome" name="nome" placeholder="Digite o nome do usuario" required>
                        </div>
                        <div class="form-group">
                          <label for="email">E-mail:</label>
                          <input type="email" class="form-control" id="email" name="email" placeholder="Digite o email do usuario" required>
                        </div>
                        <div class="form-group">
                         <label for="senha" style="color: #fff;">Senha:</label>
                         <input type="password" class="form-control" id="senha" placeholder="Digite sua senha" required>
                        </div>
                        <div class="form-group">
                          <label for="loja">Nome da loja:</label>
                          <input type="text" id="nome" class="form-control" name="senha" placeholder="Digite o nome da loja que o usuario pertence" required>
                        </div>
                        <button class="btn btn-primary" type="submit">Cadastrar</button>
                        <a class="btn btn-success" href="{% url 'plataforma:home' %}"> Fazer login </a>
                </form>
            </div>
    </section>
</main>
{% endblock %}

Projeto/plataforma/templates/plataforma/footer.html
<footer class="page-footer">
    <div class="foooter-container">
      <div>
        <div class="col l6 s12">
          <h5 class="white-text" align="center">Django Framework</h5>
          <p class="grey-text text-lighten-4" align="center">Python Web</p>
        </div>
      </div>
    </div>
    <div class="footer-copyright" align="center">
      <div class="foooter-container">
      © 2023 Copyright Thiago Alves
      <a class="grey-text text-lighten-4 right" href="https://github.com/thiago-ndev"> GitHub</a>
      </div>
    </div>
  </footer>

Projeto/plataforma/templates/plataforma/trocar_senha.html
{% extends 'plataforma/base.html' %}


{% block main_content %}
     <main>
    <section class="formulario-login">
            <div class="container">
                    <form class="login-form" method="POST" action="{% url 'plataforma:home' %}"> {% csrf_token %}
                        <div class="col-md-8">
                            <h2 style="color: #fff;">Recuperar Senha</h2>
                            <div class="form-group">
                                <label for="email" style="color: #fff;">E-mail:</label>
                                <input type="email" class="form-control" id="email" placeholder="Digite o E-mail do Usuário" required>
                            </div>
                            <div class="form-group">
                                <label for="senha" style="color: #fff;">Codigo de Recuperação:</label>
                                <input type="text" class="form-control" id="codigo" placeholder="Digite o codigo enviado" required>
                                <!--
                                Adicionar depois no javascript uma logica para esconder o campo para que ele só apareça quando o usuario clicar para enviar o e-mail
                                ou então criar uma nova pagina com uma nova rota só para o usuario digitar o codigo
                                -->
                            </div>
                            <div class="form-group">
                            <button id="confrim" type="submit" class="btn btn-primary">Entrar</button>
                            <a class="btn btn-primary" href="{% url 'plataforma:home' %}"  style="color: white; text-decoration: none;"> Voltar</a>

                            </div>
                        </div>
                    </form>

                </div>
        </section>
    </main>
{% endblock %}