Projeto/Projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('produtos/', include('appProdutos.urls', namespace='produtos')),
    path('clientes/', include('appClientes.urls', namespace='clientes')),
    path('', include('plataforma.urls', namespace='plataforma'))
         
]

Projeto/appClientes/urls.py
from django.urls import path
from . import views

app_name = "appClientes"

urlpatterns = [
    path('', views.home, name="home"),
    
    path('cadastro/', views.cadastro, name="cadastro"),
    
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    
    path('busca/', views.busca, name="busca"),
    
    path('lista/', views.lista, name="lista"),
    
    path('alterar/<int:id>/', views.alterar, name='alterar'),
    
    path('excluir/<int:id>/', views.excluir, name='excluir')
        
]

Projeto/appProdutos/urls.py
from django.urls import path
from .import views


app_name = 'appProdutos'

urlpatterns = [

    path('', views.home, name='home'),

    path('Cadastro/', views.cadastro, name='cadastro'),

    path('Cadastrar/', views.cadastrar, name='cadastrar'),

    path('Busca/', views.busca, name='busca'),

    path('Lista/', views.lista, name='lista'),

    path('Alterar/<int:codigo>/', views.alterar, name='alterar'),

    path('Excluir/<int:codigo>/', views.excluir, name='excluir'),

    path('Busca/enviar_post/', views.pesquisar, name="pesquisar"),
]

Projeto/appProdutos/models.py
from django.db import models
from django.db.models.signals import post_save

# Create your models here.

class Fornecedor(models.Model):
    class Meta:
        db_table = 'fornecedor'
        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'

    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=150, null=False)
    telefone = models.CharField(max_length=12, null=False)


    def __str__(self):
        return f'{self.id}, {self.nome}, {self.telefone}'

    def __repr__(self):
        return f'{self.id}, {self.nome}, {self.telefone}'

class Categoria(models.Model):
    class Meta:
        db_table = 'categoria'
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100, null=False, blank=True)
    sigla = models.CharField(max_length=10, null=True, unique=True)


    def __str__(self):
        return f'{self.id}, {self.nome}, {self.sigla}'

    def __repr__(self):
        return f'{self.id}, {self.nome}, {self.sigla}'



class Produto(models.Model):

    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100,null=False)
    preco = models.FloatField(null=False)


    class Meta:
        db_table = 'produto'
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    #TODO : Relacionamento entre produto e forncedor

    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.CASCADE, null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True)


    def __str__(self):
        return f'{self.id}, {self.nome}, {self.preco}'


    def __repr__(self):
        return f'{self.id}, {self.nome}, {self.preco}'


class Estoque(models.Model):
    class Meta:
        db_table = 'estoque'
        verbose_name = 'Estoque'
        verbose_name_plural = 'Estoques'

    id = models.AutoField(primary_key=True)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, null=True)
    quantidade = models.IntegerField(null=False, default=0)

    def __str__(self):
        return f'{self.id}, {self.produto}, {self.quantidade}'

    def __repr__(self):
        return f'{self.id}, {self.produto}, {self.quantidade}'


class OperacaoEstoque(models.Model):

    class Meta:
        db_table = 'operacao_estoque'
        verbose_name = 'Operação de Estoque'
        verbose_name_plural = 'Operações de Estoque'

    cadastrar = "ADD"
    remover = "DELETE"

    operacoes = (
        ('ADD', 'Cadastrar'),
        ('DELETE', 'Remover')
    )

    id = models.AutoField(primary_key=True)
    date = models.DateField(auto_now_add=True, null=False)
    type = models.CharField(max_length=20, choices=operacoes)
    quantidade = models.IntegerField( null=False)
    
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, null=True)
    funcionario = models.ForeignKey('appClientes.Funcionario', on_delete=models.CASCADE, null=True)
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return f'{self.id},{self.date}, {self.type} ,{self.produto}, {self.funcionario},{self.quantidade}, {self.date}'

    def __repr__(self):
        return f'{self.id},{self.date}, {self.type}, {self.produto},{self.funcionario} ,{self.quantidade}, {self.date}'

Projeto/appProdutos/forms.py
from django import forms

class CadastroForm(forms.Form):
    codigo = forms.IntegerField(required=False, widget= forms.HiddenInput())
    nome = forms.CharField(label='Produto : ',max_length=100, widget=forms.TextInput(
        attrs={'class' : 'form-control', 'placeholder': 'nome'}
    ))
    preco = forms.FloatField(label='Preço: ', widget=forms.TextInput(
        attrs={'class': 'form-control', 'type':'number'}
    ))
    quantidade = forms.IntegerField(label='Quantidade: ', widget=forms.TextInput(
        attrs={'class': 'form-control', 'type':'number'}

    ))

Projeto/appProdutos/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from .forms import CadastroForm
from django.contrib import messages
from django.contrib.messages import constants
from .models import Produto
import json
# Create your views here.

# macetinho do Sérgio muito robado
CADASTRO_PAGE = 'appProdutos/cadastro.html'
BUSCA_PAGE = 'appProdutos/busca.html'
LISTA_PAGE = 'appProdutos/lista.html'



def home(request):
    template = loader.get_template('appProdutos/index.html')
    return HttpResponse(template.render())

def cadastro(request):
    form = CadastroForm()
    return render(request,CADASTRO_PAGE, {'form': form})

def cadastrar(request):
    try:
        if request.method == 'POST':
            form = CadastroForm(request.POST)
            if form.is_valid():
                produto = Produto()
                produto.nome = form.cleaned_data['nome']
                produto.preco = form.cleaned_data['preco']
                produto.quantidade = form.cleaned_data['quantidade']
            
                codigo = form.cleaned_data['codigo']

                if produto.preco < 0 or produto.quantidade <0:
                    messages.add_message(request, constants.ERROR, 'O produto não pode ter valor negativo.')
                    return render(request, CADASTRO_PAGE,{'form': form})
                    
                if codigo:
                    messages.add_message(request, constants.WARNING, "Produto Alterado.")
                    produto.codigo = codigo
                    produto.save()
                    return render(request,CADASTRO_PAGE,{'form':CadastroForm})
                    
                    
                produto.save()
                
                
            else:
                msg = form.errors
                return render(request,CADASTRO_PAGE,{'form':CadastroForm, 'msg':msg})
            
            messages.add_message(request, constants.SUCCESS, "Produto Cadastrado.")
            return render(request,CADASTRO_PAGE,{'form':CadastroForm,'msg':msg})
        
        else:
            raise Exception('MethodEnvioError, Use POST para Formularios.')
        
    except Exception as ex:
        msg = ex.args
        return render(request,CADASTRO_PAGE,{'form':CadastroForm,'msg':msg})

def busca(request):
    return render(request, BUSCA_PAGE)

def lista(request):
    produtos = Produto.objects.order_by('codigo').all()
    return render(request, LISTA_PAGE, {'produtos': produtos})

def alterar(request,codigo):

    try:
        produto = Produto.objects.get(pk=codigo)
        form = CadastroForm(initial={
            'nome': produto.nome,
            'preco': produto.preco,
            'quantidade': produto.quantidade,
            'codigo': produto.codigo

        })
        
        return render(request,CADASTRO_PAGE,{'form':form})

    except Exception as ex:
        msg = ex.args
        render(request, LISTA_PAGE, {'produtos': Produto.objects.all(), 'msg': msg })

def excluir(request,codigo):
    produtos = Produto.objects.all()
    try:
        produto = Produto.objects.get(pk = codigo)
        result = produto.delete()

        if result[0] > 0:
            messages.add_message(request, constants.ERROR, "Produto deletado.")
            
        else:
            messages.add_message(request, constants.ERROR, "Produto não encontrado.")
            
            
        return render(request,LISTA_PAGE,{'produtos':produtos})

    except Exception as ex:
        msg = ex.args
        render(request, LISTA_PAGE, {'produtos':produtos, 'msg': msg})

def pesquisar(request):

    try:
        if request.method == 'POST':
            nome = request.POST['nome']
            # efetuar uma busca no banco de dados
            # LIKE %nome% -> contenha a palavra 'copo'
            produtos = Produto.objects.filter(nome__icontains =nome)
            response = {}

            for indice, produto in enumerate(produtos):
                p = {}
                p['codigo'] = produto.codigo
                p['nome'] = produto.nome
                p['preco'] = produto.preco
                p['quantidade'] = produto.quantidade
                response[indice] = p

            response['t'] = len(produtos)

            return HttpResponse(json.dumps(response),
                                content_type='application/json')


        else:
            raise Exception('MethodEnvioError, use POST para formulários')

    except Exception as ex:
        msg = ex.args
        return HttpResponse(json.dumps({"msg": msg}),
                            content_type='application/json')

Projeto/appProdutos/templates/appProdutos/busca.html
{% extends 'appProdutos/base.html' %}
{% load static %}
{% block main_content %}
<p align="center"> Produtos encontrados: </p>

<form method="POST" action="#"  id="form" class="form-inline">
    {% csrf_token %}
    <input type="text" name="nome" id="nome" placeholder="Nome" class="form-control mr-sm-2" />
    <input type="submit" value="Efetuar busca" class="form-control btn-primary"  />
</form>
<div id="saida">
</div>


{% endblock %}

Projeto/appProdutos/templates/appProdutos/cadastro.html
{% extends 'appProdutos/base.html' %}
{% load static %}

    ###Dash Analytics
    {% block active-dash_analytics-key_users %} data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-dash_analytics-key_users %} class="collapse submenu list-unstyled" {% endblock %}




    ###Alianca App
    {% block active-alianca_app-key_users %}data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-alianca_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}



    ###Manager App
    {% block active-manager_app-key_users %}data-active="true" data-toggle="collapse" aria-expanded="true" {% endblock %}
    {% block show-manager_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}
    {% block active_manager_app-key_users %} active {% endblock %}




    {% block stored_structures-key_users %} color:#4361ee {% endblock %}
{% block main_content %}



<p align="center"> Cadastro de produto </p>
<hr color="black">

<form method="POST" action="{% url 'produtos:cadastrar' %}">

    {% csrf_token %}
    {{ form.codigo }}

    <div class="form-group row">
        <label for="id_nome" class="col-sm-10"> {{ form.nome.label }}</label>
        <div class="col-sm-3">
            {{ form.nome }}
        </div>
    </div>

    <div class="form-group row">
        <label for="id_nome" class="col-sm-10"> {{ form.preco.label}}</label>
        <div class="col-sm-3">
            {{form.preco}}
        </div>
    </div>

    <div class="form-group row">
        <label for="id_nome" class="col-sm-10"> {{ form.quantidade.label }}</label>
        <div class="col-sm-3">
            {{form.quantidade}}
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-10"></label>
        <div class="col-sm-6">
        <input type="submit" value="Cadastrar" class="btn btn-primary">
        </div>

    </div>

</form>

{% if messages %}
    {% for message in messages %}
    <div class="alert {{message.tags}}">{{ message }}</div>
    {% endfor %}
{% endif %}

<hr style="border-color:blanchedalmond">
{% endblock %}

Projeto/appProdutos/templates/appProdutos/header.html
{% load static %}
<div class="header">
  <div class="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'appProdutos:home' %}">Home</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkProdutos" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {#                  <a class="nav-link dropdown-toggle" href="{% url 'appProdutos:lista' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">#}
                          Gerenciar Produtos
                      </a>
                      <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'appProdutos:cadastro' %}">Cadastrar</a></li>
                          <li><a class="dropdown-item" href="{% url 'appProdutos:lista' %}">Listar Produtos</a></li>
                          <li><a class="dropdown-item" href="{% url 'appProdutos:busca' %}">Buscar Produtos</a></li>
                        </ul>
                  </li>

                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkClientes" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Gerenciar Clientes
                      </a>
                      <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{%  url 'appClientes:cadastro' %}">Cadastrar </a></li>
                          <li><a class="dropdown-item" href="{% url 'appClientes:lista' %}"> Listar Clientes </a></li>
                      </ul>
                  </li>
              </ul>
              </div>
              <form class="form-inline my-2 my-lg-2" action="{% url 'plataforma:home' %}" >
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit" >Sair</button>
                </form>
          </div>
      </nav>
    </div>
</div>

Projeto/appProdutos/templates/appProdutos/index.html
{% extends 'appProdutos/base.html' %}
{% load static %}

###Dash Analytics
    {% block active-dash_analytics-key_users %} data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-dash_analytics-key_users %} class="collapse submenu list-unstyled" {% endblock %}




    ###Alianca App
    {% block active-alianca_app-key_users %}data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-alianca_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}



    ###Manager App
    {% block active-manager_app-key_users %}data-active="true" data-toggle="collapse" aria-expanded="true" {% endblock %}
    {% block show-manager_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}
    {% block active_manager_app-key_users %} active {% endblock %}




    {% block stored_structures-key_users %} color:#4361ee {% endblock %}

{% if messages %}
    {% for message in messages %}
    <div class="alert {{message.tags}}">{{ message }}</div>
    {% endfor %}
{% endif %}

{% block main_content %}

<div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1> Boas vindas ! </h1>
      </div>
    </div>
  </div>

{% endblock %}

Projeto/appProdutos/templates/appProdutos/lista.html
{% extends 'appProdutos/base.html' %}
{% load static %}


    ###Dash Analytics
    {% block active-dash_analytics-key_users %} data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-dash_analytics-key_users %} class="collapse submenu list-unstyled" {% endblock %}




    ###Alianca App
    {% block active-alianca_app-key_users %}data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-alianca_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}



    ###Manager App
    {% block active-manager_app-key_users %}data-active="true" data-toggle="collapse" aria-expanded="true" {% endblock %}
    {% block show-manager_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}
    {% block active_manager_app-key_users %} active {% endblock %}




    {% block stored_structures-key_users %} color:#4361ee {% endblock %}

{% block main_content %}

<p align="center"> Tabela de produtos cadastrados </p>

{% if produtos or produtos|length > 0 %}
<table  align="center" class="table table-bordered table-striped table-sm table-dark">

  <tr align="center">
        <th> codigo </th>
        <th> nome  </th>
        <th> preço </th>
        <th> quantidade </th>
        <th> Operações </th>
  </tr>

    {% for produto in produtos %}
        <tr align="center" >
            <td> {{ produto.codigo }}  </td>
            <td> {{ produto.nome }}  </td>
            <td> {{ produto.preco }}  </td>
            <td> {{ produto.quantidade }}  </td>
            <td> <a href="{% url 'produtos:alterar' codigo=produto.codigo %}"
                    class="btn btn-warning btn-sm" > alterar </a> |
                 <a href="{% url 'produtos:excluir' codigo=produto.codigo %}"
            onclick="return window.confirm('Deseja realmente excluir ? ');"
                    class="btn btn-danger btn-sm" > excluir </a> </td>
        </tr>

        {% endfor %}

</table>
{% else %}
    <p> Nenhum produto cadastrado </p>
{% endif %}

{% if messages %}
    {% for message in messages %}
    <div class="alert {{message.tags}}">{{ message }}</div>
    {% endfor %}
{% endif %}

{% endblock %}