Projeto/Projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('produtos/', include('appProdutos.urls', namespace='produtos')),
    path('clientes/', include('appClientes.urls', namespace='clientes')),
    path('', include('plataforma.urls', namespace='plataforma'))
         
]

Projeto/appClientes/urls.py
from django.urls import path
from . import views

app_name = "appClientes"

urlpatterns = [
    path('', views.home, name="home"),
    
    path('cadastro/', views.cadastro, name="cadastro"),
    
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    
    path('busca/', views.busca, name="busca"),
    
    path('lista/', views.lista, name="lista"),
    
    path('alterar/<int:id>/', views.alterar, name='alterar'),
    
    path('excluir/<int:id>/', views.excluir, name='excluir')
        
]

Projeto/appClientes/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser, UserManager, Group, Permission

# Create your models here.


class Gerenciar_fornecedor:
    """
    Classe responsavel por gerenciar as fornecedor
    """

    def cadastrar_fornecedores(self, fornecedor):
        pass

    def deletar_fornecedores(self, idfornecedor, fornecedor):
        pass

    def atualizar_fornecedores(self, idfornecedor, fornecedor):
        pass

    def listar_fornecedores(self):
        pass


class Gerente(AbstractUser):

    class Meta:
        db_table = 'gerente'
        verbose_name = 'Gerente'
        verbose_name_plural = 'Gerentes'

    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="gerente_groups",  # Novo related_name
        related_query_name="gerente",
    )

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="gerente_user_permissions",  # Novo related_name
        related_query_name="gerente",
    )

    nome = models.CharField(
        max_length=150,
        null=False)

    username = models.CharField(
        max_length=150,
        unique=True,
        error_messages={
            "unique": "O nome de usuario já existe",
            "required": "O nome de usuario é obrigatorio."
        },
        null=False)

    email = models.EmailField(
        unique=True,
        error_messages={
            "unique": "O email informado já está em uso.",
            "required": "O email é obrigatorio."
        },
        max_length=150,
        null=False

    )

    objects = UserManager()

                                                        # manager funcionarios
    def cadastrar_funcionario(self, funcionario):
        pass

    def deletar_funcionario(self, idfuncionario, funcionario):
        pass

    def atualizar_funcionario(self, idfuncionario, funcionario):
        pass


                                                        # manager catergoria
    def cadastrar_categoria(self, categoria):
        pass

    def deletar_categoria(self, idcategoria, categoria):
        pass

    def atualizar_categoria(self, idcategoria,categoria):
        pass

                                                        # manager produtos
    def cadastrar_produto(self, produto):
        pass

    def deletar_produto(self, idproduto, produto):
        pass

    def atualizar_produto(self, idproduto,produto):
        pass


                                                        # manager fornecedores
    def cadastrar_fornecedor(self, fornecedor):
        pass

    def deletar_fornecedor(self, idfornecedor, fornecedor):
        pass

    def atualizar_fornecedor(self, idfornecedor, fornecedor):
        pass



    def Agendar_entrega_de_produtos(self):
        pass

    def gerar_relatorios(self):
        pass


    def acessar_Auditorias(self):
        pass

    def gerenciar_fornecedores(self):
        pass

    def realizar_backup(self):
        pass


    def avaliar_fornecedores(self):
        pass



    def __str__(self):
        return f'{self.nome}, {self.email}, {self.username}'

    def __repr__(self):
        return f'{self.nome}, {self.email}, {self.username}'



class Funcionario(User):

    class Meta:
        db_table = 'funcionario'
        verbose_name = 'Funcionario'
        verbose_name_plural = 'Funcionarios'

    nome = models.CharField(max_length=150, null=False)
    data_Nasc = models.DateField(null=False)




    def Registrar_Entrada_Produto(self):
        pass

    def Registrar_Saida_Produto(self):
        pass

    def __str__(self):
        return f'{self.nome}, {self.email}'

    def __repr__(self):
        return f'{self.nome}, {self.email}'


class Endereco(models.Model):

    id = models.AutoField(primary_key=True)
    uf = models.CharField(max_length=100, null=False)
    cidade = models.CharField(max_length=100, null=False)
    bairro = models.CharField(max_length=100, null=False)
    rua = models.CharField(max_length=100, null=False)
    cep = models.CharField(max_length=100, )

    fornecedor = models.ForeignKey('appProdutos.Fornecedor', on_delete=models.CASCADE, null=True, blank=True)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE, null=True, blank=True)
    gerente = models.ForeignKey(Gerente, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return f'{self.id},{self.uf}, {self.cidade}, {self.bairro}, {self.rua}, {self.cep}'

    def __repr__(self):
        return f'{self.id},{self.uf},{self.cidade}, {self.bairro}, {self.rua}, {self.cep}'

Projeto/appClientes/forms.py
from django import forms
import datetime

class ClienteForm(forms.Form):
    
    codigo = forms.IntegerField(required=False, widget=forms.HiddenInput())
    
    nome = forms.CharField(label="Nome: ", max_length=100, 
                           widget= forms.TextInput(attrs={'class' : 'form-control', 'placeholder': 'nome'}))
    
    
    email = forms.CharField(label="Email: ", max_length=100,
                            widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'email'}))
    
    senha = forms.CharField(label="Senha: ", max_length=100, widget= forms.TextInput(attrs={'type': 'password'}))
    data_Nasc = forms.DateField(label='Data',widget=forms.DateInput(format='%Y/%m/%d' ,attrs={'type': 'date'}),
                                input_formats=['%y/%m/%d', '%Y-%m-%d'])
    

class EnderecoForm(forms.Form):    
    
    cidade = forms.CharField(label="Cidade: ", max_length=30,
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City'}))
    
    bairro = forms.CharField(label="Bairro: ", max_length=30,
                             widget=forms.TextInput())
    
    rua   = forms.CharField(label="Rua: ", max_length=20,
                            widget=forms.TextInput())
    
    numero = forms.IntegerField(label="Numero: ",
                                widget=forms.TextInput())
    
    
    

Projeto/appClientes/views.py
from django.shortcuts import render
from django.http import HttpResponse 
from django.template import loader
from django.contrib import messages
from django.contrib.messages import constants
from .forms import ClienteForm, EnderecoForm
from .models import Gerente, Endereco, Funcionario
import datetime


CADASTRO_PAGE = 'appClientes/cadastro.html'
BUSCA_PAGE = 'appClientes/busca.html'
LISTA_PAGE = 'appClientes/lista.html'

# Create your views here.

class GerenciarProdutos:

    def __cadastrar_produtos(self, produto):
        pass

    def __deletar_produtos(self, idproduto, produto):
        pass

    def __atualizar_produtos(self, idproduto, produto):
        pass

    def __listar_produtos(self):
        pass


class GerenciarFuncionarios:
    """"
    Classe responsavel por gerenciar os funcionarios
    """

    def __cadastrar_funcionarios(self):
        pass

    def __deletar_funcionarios(self):
        pass

    def __atualizar_funcionarios(self):
        pass

    def __listar_funcionarios(self):
        pass


class GerenciarCategorias:
    """
    Classe responsavel por gerenciar as categorias
    """

    def cadastrar_categorias(self):
        pass

    def deletar_categorias(self):
        pass

    def atualizar_categorias(self):
        pass

    def listar_categorias(self):
        pass

class GerenciarFornecedor:
    """
    Classe responsavel por gerenciar os Fornecedor
    """

    def cadastrar_fornecedor(self):
        pass

    def deletar_fornecedor(self):
        pass

    def atualizar_fornecedor(self):
        pass

    def listar_fornecedor(self):
        pass



class GerenciarEstoque:
    """
    Classe responsavel por gerenciar os Estoque
    """

    def cadastrar_estoque(self):
        pass

    def deletar_estoque(self):
        pass

    def atualizar_estoque(self):
        pass

    def listar_estoque(self):
        pass














def home(request):
    template = loader.get_template('appClientes/index.html')
    return HttpResponse(template.render())


def cadastro(request):        
    form_cliente = ClienteForm()
    form_endereco =  EnderecoForm()
    
    return render(request, CADASTRO_PAGE, {'form_cliente': form_cliente, 'form_endereco': form_endereco} )


def cadastrar(request):
    try:
        form_cliente = ClienteForm(request.POST)
        form_endereco = EnderecoForm(request.POST)
        if request.method == "POST":
            cliente = Funcionario()
            endereco = Endereco()
            if form_cliente.is_valid() and form_endereco.is_valid():
                cliente.nome = form_cliente.cleaned_data['nome']
                cliente.email = form_cliente.cleaned_data['email']
                cliente.senha =  Crypt_Password(form_cliente.cleaned_data['senha'])
                cliente.data_Nasc =form_cliente.cleaned_data['data_Nasc']
                endereco.cidade = form_endereco.cleaned_data['cidade']
                endereco.bairro = form_endereco.cleaned_data['bairro']
                endereco.rua = form_endereco.cleaned_data['rua']
                endereco.numero = form_endereco.cleaned_data['numero']
                
                codigo = form_cliente.cleaned_data['codigo']             
            
                if codigo:
                    cliente.pk = codigo
                    cliente.save()
                    endereco.cliente = cliente
                    endereco.save()
                    return render(request, CADASTRO_PAGE, {'form_cliente': form_cliente, 'form_endereco': form_endereco},
                                  messages.add_message(request, constants.WARNING, 'Alterado.'))

                
                if cliente.data_Nasc:
                    cliente.data_Nasc.strftime("%d/%m/%y")
                                
                cliente.save()
                endereco.cliente = cliente
                
                endereco.save()
            

            else:
                msg = form_cliente.errors
                msg1 = form_endereco.errors
                
                return render(request, CADASTRO_PAGE,{'form_cliente': form_cliente, 'form_endereco': form_endereco} ,
                              messages.add_message(request, constants.ERROR, f'{msg}, {msg1}'))                    
            
        else:
            raise Exception(CADASTRO_PAGE,{'form_cliente': form_cliente, 'form_endereco': form_endereco},
                            messages.add_message(request, constants.ERROR, "MethodEnvioError, Use POST para enviar formulários."))
        
        return render(request, CADASTRO_PAGE,{'form_cliente': form_cliente, 'form_endereco': form_endereco}, messages.add_message(request, constants.SUCCESS, "Cadastrado"))                    
        
        
        # Verificar porque está gerando um Exception no retorndo do endereco quando vai alterar um cliente.
        # pode ser a falta do id do endereco la no método cadastrar
        
    except Exception as ex:
        msg = ex.args
        return render(request, CADASTRO_PAGE,{'form_cliente': form_cliente, 'form_endereco': form_endereco},
                      messages.add_message(request, constants.ERROR, msg))
    
    
def busca(request):
    return render(request, BUSCA_PAGE)


def lista(request):
    clientes = Cliente.objects.order_by('id').all()
    enderecos = Endereco.objects.all()
    return render(request, LISTA_PAGE, {'clientes': clientes, 'enderecos':enderecos})
      

def alterar(request, id):
    try:
        cliente = Cliente.objects.get(pk=id)
        endereco = Endereco.objects.get(pk=id)
        data_nasc = cliente.data_Nasc
        
        form_cliente = ClienteForm(initial={
            'nome': cliente.nome,
            'email': cliente.email,
            'senha': cliente.senha,
            'data_Nasc': data_nasc,
            'codigo' : cliente.pk            

        })
        form_endereco = EnderecoForm(initial={
            'cidade': endereco.cidade, 
            'bairro': endereco.bairro,
            'rua': endereco.rua,
            'numero': endereco.numero,
            
            
        })
        
        
        return render(request, CADASTRO_PAGE, {'form_cliente':form_cliente, 'form_endereco': form_endereco})
        
        
    except Exception as ex:
        msg = ex.args
        return render(request, LISTA_PAGE, {'clientes': Cliente.objects.all()} , 
                      messages.add_message(request, constants.ERROR,f'{msg}'))
        
        
def excluir(request, id):
    clientes = Cliente.objects.all()
    try:
        cliente = Cliente.objects.get(pk=id)
        result = cliente.delete()
        if result[0] > 0:
            messages.add_message(request, constants.ERROR, 'Cliente Deletado')
            
        else:
            messages.add_message(request, constants.ERROR, 'Nenhum Cliente encontrado')
            
        return render(request, LISTA_PAGE, {'clientes': clientes})                
        
        
    except Exception as ex:
        msg = ex.args
        render(request, LISTA_PAGE, messages.add_message(request, constants.ERROR, f'{msg}'),
                      {'clientes': Cliente.objects.all()})
    

Projeto/appClientes/templates/appClientes/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title> Sistema Web </title>
    <link rel="stylesheet" href="{% static 'appProdutos/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'appClientes/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'appProdutos/bootstrap/css/bootstrap.min.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


</head>
<body>
<div class="container">
  {% include 'appProdutos/header.html' %}
<div class="content">


{% block main_content %}
{% endblock %}
</div>

{% include 'plataforma/footer.html' %}

</div>
</body>
</html>

Projeto/appClientes/templates/appClientes/cadastro.html
{% extends 'appProdutos/base.html' %}

###Dash Analytics
    {% block active-dash_analytics-key_users %} data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-dash_analytics-key_users %} class="collapse submenu list-unstyled" {% endblock %}




    ###Alianca App
    {% block active-alianca_app-key_users %}data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-alianca_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}



    ###Manager App
    {% block active-manager_app-key_users %}data-active="true" data-toggle="collapse" aria-expanded="true" {% endblock %}
    {% block show-manager_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}
    {% block active_manager_app-key_users %} active {% endblock %}




    {% block stored_structures-key_users %} color:#4361ee {% endblock %}

{% block main_content %}

<p align="center"> Cadastro de Clientes </p>
<hr color="black">

<form method="POST" action="{% url 'clientes:cadastrar' %}" row="center">

    {% csrf_token %}
    {{ form_cliente.codigo }}
    
    <div class="form-group row">
        <label for="id_nome" class="col-sm-0"> {{ form_cliente.nome.label }}</label>
        <div class="col-sm-3">
            {{ form_cliente.nome }}
        </div>
        <label for="id_name" class="col-sm-0"> {{form_endereco.cidade.label}}</label>
        <div class="col-sm-3">
            {{form_endereco.cidade }}
        </div>
    </div>


    <div class="form-group row">
        <label for="id_nome" class="col-sm-0"> {{ form_cliente.email.label}}</label>
        <div class="col-sm-3">
            {{form_cliente.email}} 
        </div>
        <label for="id_name" class="col-sm-0">{{form_endereco.bairro.label}}</label>
        <div class="col-sm-3">
            {{form_endereco.bairro}}
        </div>
    </div>

    <div class="form-group row">
        <label for="id_nome" class="col-sm-0"> {{ form_cliente.senha.label }}</label>
        <div class="col-sm-3">
            <div class="input-group-append">
            {{form_cliente.senha}}
            </div>
        </div>
        <label for="id_name" class="col-sm-0">{{form_endereco.numero.label}}</label>
        <div class="col-sm-1">
             {{form_endereco.numero}}
        </div>
    </div>

    <div class="form-group row">
        <label for="id_nome" class="col-sm-0"> {{ form_cliente.data_Nasc.label }}</label>
        <div class="col-sm-3">
            {{form_cliente.data_Nasc}}
        </div>
        <label for="id_name" class="col-sm-0"> {{form_endereco.rua.label}}</label>
        <div class="col-sm-1">
            {{form_endereco.rua}}
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-10"></label>
        <div class="col-sm-6">
        <input type="submit" value="Cadastrar" class="btn btn-primary">
        </div>

    </div>

</form>

{% if messages %}
    {% for message in messages %}
    <div class="alert {{message.tags}}">{{ message }}</div>
    {% endfor %}
{% endif %}

<hr style="border-color:blanchedalmond">
{% endblock %}

Projeto/appClientes/templates/appClientes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Projeto/appClientes/templates/appClientes/lista.html
{% extends 'appProdutos/base.html' %}

###Dash Analytics
    {% block active-dash_analytics-key_users %} data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-dash_analytics-key_users %} class="collapse submenu list-unstyled" {% endblock %}


    ###Alianca App
    {% block active-alianca_app-key_users %}data-active="false" data-toggle="collapse" aria-expanded="false" {% endblock %}
    {% block show-alianca_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}



    ###Manager App
    {% block active-manager_app-key_users %}data-active="true" data-toggle="collapse" aria-expanded="true" {% endblock %}
    {% block show-manager_app-key_users %} class="collapse submenu list-unstyled"{% endblock %}
    {% block active_manager_app-key_users %} active {% endblock %}




    {% block stored_structures-key_users %} color:#4361ee {% endblock %}


{% block main_content %}
<p align="Center"> Clientes Cadastrados </p>

{% if clientes or clientes|length > 0 %}
<table align="center" class="table table-bordered table-striped table-sm table-dark">

    <tr align="center">
        <th> id </th>
        <th> nome  </th>
        <th> email </th>
        <th> data de Nascimento </th>
        <th> endereço </th>
        
        
        <th> Operações </th>
  </tr>
    
    {% for cliente in clientes  %} 
    <tr align="center">
        <td> {{ cliente.id }} </td>
        <td> {{cliente.nome}}  </td>
        <td> {{ cliente.email }} </td>
        <td> {{ cliente.data_Nasc }} </td>
        <td> {{ cliente.endereco.cidade}}, {{cliente.endereco.bairro}},
             {{cliente.endereco.rua}}, {{cliente.endereco.numero}} </td>
             <td> <a href="{% url 'clientes:alterar' id=cliente.id %}"
                class="btn btn-warning btn-sm" > alterar </a> |
             <a href="{% url 'clientes:excluir' id=cliente.id%}"
        onclick="return window.confirm('Deseja realmente excluir ? ');"
                class="btn btn-danger btn-sm" > excluir </a> </td>
  </tr>
    {% endfor %}

</table>
{% else %}
    <p> Nenhum Cliente cadastrado </p>
{% endif %}

{% if messages %}
    {% for message in messages %}
    <div class="alert {{message.tags}}">{{ message }}</div>
    {% endfor %}
{% endif %}

{% endblock %}